### ISSUE TITLE
The problem of dataset

### ISSUE THREAD

**Issue by RainbowSun1102** [kanezaki/pytorch-rotationnet#10]
Hi, thank you for your work and codes.

I notice that the subset of ModelNet40 (http://maxwell.cs.umass.edu/mvcnn-data/?C=D;O=A) you provided is 7.2G. But the full set is just 2.46G. I just wonder why the gap is such large?

Thank you for your time.

Rainbow

**Comment by kanezaki** [comment]
Hi Rainbow,

That file provided by Su et al. contains multi-view rendered images, while the original ModelNet40 dataset only contains the coordinates of 3D models. This is why there is a size gap between them.

**Comment by RainbowSun1102** [comment]
Thank you for your reply.
I said the full set is provided by your group (https://data.airc.aist.go.jp/kanezaki.asako/data/modelnet40v2png_ori4.tar). The size is just 2.46G, but the subset you mentioned is as big as 7.2G. 
So, I am just interested in why the subset is much bigger than your full set.

Thank you,
Rainbow

**Comment by kanezaki** [comment]
I see, the reason is that the full set we provided contains 20 view images per model, while the subset I mentioned before contains 80 view images per model. Our dataset doesn't include in-plane rotation. Thanks!
