### ISSUE TITLE
Testing rotationnet

### ISSUE THREAD

**Issue by ozgraslan** [kanezaki/pytorch-rotationnet#11]
Can I test the model by using only one view of an object?

**Comment by kanezaki** [comment]
Yes, you can obtain the scores of category and pose for one view by modifying line 373 from "output = output.view( -1, nview * nview, num_classes )" to "output = output.view( -1, nview, num_classes )". Also, please comment out line 135-137.

**Comment by ozgraslan** [comment]
Thanks!

**Comment by baibizhe** [comment]
Hello . Did you test successfully on  single image inference?
