### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by cy69855522** [kanezaki/pytorch-rotationnet#13]
Thx for ur wonderful work, however, I find the URL is invalid so that I cannot download the data set.
`https://data.airc.aist.go.jp/kanezaki.asako/data/modelnet40v2png_ori4.tar;`

**Comment by kanezaki** [comment]
Sorry for the inconvenience, but our server (data.airc.aist.go.jp) is under maintenance this week. I temporarily uploaded the file here:
https://www.dropbox.com/s/m3mhgkmfmhfq8ln/modelnet40v2png_ori4.tar?dl=0
Thanks!

**Comment by cy69855522** [comment]
Thank you!

**Comment by HankKung** [comment]
Hi, the links from both this issue and the one used in the script are not valid anymore. Could you please update either of them? Thank you!!!
