### ISSUE TITLE
link_images_MIRO.sh problem.

### ISSUE THREAD

**Issue by jkristek38** [kanezaki/pytorch-rotationnet#14]
I downloded MIRO dataset from command line. Unziped in console with provided command. I run the command `bash link_images_MIRO.sh ./MIRO ./data_MIRO` and it creates data_MIRO structure with train and val, but in console i see errors for example: `ln: failed to create symbolic link'./stapler_10_001.png': No such file or directory` This is written for every image in dataset and in data_MIRO there is not a single image. What it´s wrong?

**Comment by kanezaki** [comment]
The expected behavior is to create `./data_MIRO/train/stapler`, change current directory to it, and create symbolic link by `ln -s ../../.././MIRO/stapler/stapler_10_001.png .` command. Then it will look like this.
```
MIRO
|-- bus
|   |-- bus_1_001.png
|   |-- bus_1_002.png
|   `-- bus_1_003.png
`-- car
    |-- car_1_001.png
    |-- car_1_002.png
    `-- car_1_003.png
data_MIRO
|-- train
|   |-- bus
|   |   |-- bus_2_001.png -> ../../.././MIRO/bus/bus_2_001.png
|   |   |-- bus_2_002.png -> ../../.././MIRO/bus/bus_2_002.png
|   |   `-- bus_2_003.png -> ../../.././MIRO/bus/bus_2_003.png
|   `-- car
|       |-- car_2_001.png -> ../../.././MIRO/car/car_2_001.png
|       |-- car_2_002.png -> ../../.././MIRO/car/car_2_002.png
|       `-- car_2_003.png -> ../../.././MIRO/car/car_2_003.png
`-- val
    |-- bus
    |   |-- bus_1_001.png -> ../../.././MIRO/bus/bus_1_001.png
    |   |-- bus_1_002.png -> ../../.././MIRO/bus/bus_1_002.png
    |   `-- bus_1_003.png -> ../../.././MIRO/bus/bus_1_003.png
    `-- car
        |-- car_1_001.png -> ../../.././MIRO/car/car_1_001.png
        |-- car_1_002.png -> ../../.././MIRO/car/car_1_002.png
        `-- car_1_003.png -> ../../.././MIRO/car/car_1_003.png
```
It works in Ubuntu + bash/zsh. Which OS are you using?

**Comment by jkristek38** [comment]
I am using Windows 8.1 command line to run the script.

**Comment by kanezaki** [comment]
I see. I’m not sure if it’s possible to create symbolic links in Windows. I recommend moving files from `./MIRO` to `./data_MIRO` manually.

**Comment by jkristek38** [comment]
I moved the files manually. It works, thank you.
