### ISSUE TITLE
How to get the render image of my own dataset？

### ISSUE THREAD

**Issue by fengshi-cherish** [kanezaki/pytorch-rotationnet#16]
I have some 3d model with .obj files, is there any script(python version will be better) to render models？especially case ii in paper.

**Comment by kanezaki** [comment]
I used the MATLAB script for rendering provided by H. Su (MVCNN author) with almost no change. Here is the code:
https://github.com/kanezaki/SHREC2017_track3/blob/master/mvcnn_utils/render_views.m
