### ISSUE TITLE
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:405

### ISSUE THREAD

**Issue by longmalongma** [kanezaki/pytorch-rotationnet#6]
When I try to run your code ,I met this problem,do you know how to solve this problem?
 File "/home/longma/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:405

**Comment by kanezaki** [comment]
I'm not sure but guess that you may have installed pytorch with wrong CUDA version?

**Comment by longmalongma** [comment]
Think you for your reply,my cuda vision is 9.0,do you know which one version of pytorch can work?



------------------ 原始邮件 ------------------
发件人: "Asako Kanezaki"<notifications@github.com>;
发送时间: 2019年6月16日(星期天) 晚上10:52
收件人: "kanezaki/pytorch-rotationnet"<pytorch-rotationnet@noreply.github.com>;
抄送: "longma"<1442342449@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kanezaki/pytorch-rotationnet] RuntimeError: cuda runtime error(11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:405 (#6)




I'm not sure but guess that you may have installed pytorch with wrong CUDA version?

**Comment by kanezaki** [comment]
Please try this:
`conda install pytorch=0.4.1 cuda90 -c pytorch`
