### ISSUE TITLE
How to test trained models on ModelNet40?

### ISSUE THREAD

**Issue by longmalongma** [kanezaki/pytorch-rotationnet#7]
Think you for your work,How to test trained models on ModelNet40?why can you give code about test?

**Comment by kanezaki** [comment]
You can use '-e' or '--evaluate' as a command line argument to test your model. Please don't forget to load your model by adding '--resume yourmodel.pth.tar'.

**Comment by longmalongma** [comment]
python train_rotationnet.py -e --resume rotationnet_checkpoint.pth.tar ./ModelNet40_20 | tee log_ModelNet40_20_rotationnet.txt
Error: batch size should be multiplication of the number of views, 20
Can you tell me the complete code about how to test model I have trained? and I want to know why need we to train model for 1000 epoch.It need few days.

**Comment by kanezaki** [comment]
You should set the batch size to some number multiplied by 20 by adding e.g., "-b 200". If your model is based on AlexNet architecture, you also have to add "-a alexnet". You can stop the training earlier than 1000 epochs. In my experience, it converges within one day.

**Comment by omdaisy** [comment]
> Think you for your work,How to test trained models on ModelNet40?why can you give code about test?

Did you solve the test problem? I have the same problem as you.
