### ISSUE TITLE
Runtime Error: shape '[-1, 144, 40]' is invalid for input of size 16800

### ISSUE THREAD

**Issue by ozgraslan** [kanezaki/pytorch-rotationnet#9]
When tried to train the network with:
`python train_rotationnet.py --case 1 --pretrained -a alexnet -b 240 --lr 0.01 --epochs 1500 ./ModelNet40v1 | tee log_ModelNet40v1_rotationnet.txt`

I encountered this error:
**Traceback (most recent call last):
  File "train_rotationnet.py", line 485, in <module>
    main()
  File "train_rotationnet.py", line 253, in main
    prec1 = validate(val_loader, model, criterion)
  File "train_rotationnet.py", line 377, in validate
    output = output.view( -1, nview * nview, num_classes )
RuntimeError: shape '[-1, 144, 40]' is invalid for input of size 16800**

What can be the problem?

**Comment by kanezaki** [comment]
According to the error message, it seems the size of _output_ in your case is 16800, while it should be (2880, 40) to work. I am not sure the reason why it happens. Did you modify the code or change anything in _ModelNet40v1_ directory?

**Comment by ozgraslan** [comment]
I did not change anything. But I will download the files again and try again. Maybe something went wrong while downloading.

**Comment by ozgraslan** [comment]
The problem is solved. I think there was a problem with the linking images. When I downloaded again and looked at the new files after linking there were some differences. Now it is working fine. Thank you.
